/
// Created by peter on 21/07/2025.
//

#ifndef ANDROIDSAMSUNG_XRSWAPCHAINIMAGEOPENGLESKHR_H
#define ANDROIDSAMSUNG_XRSWAPCHAINIMAGEOPENGLESKHR_H


class XrSwapchainImageOpenGLESKHR {

};


#endif //ANDROIDSAMSUNG_XRSWAPCHAINIMAGEOPENGLESKHR_H
